### ISSUE TITLE
REPORT DEBUG

### ISSUE THREAD

**Issue by Reflyansyah** [DarkWav/SAC#83] opened 2018-08-18 05:25 UTC
[12:16:39] [Server thread/CRITICAL]: could not pass event 'pocketmine\event\entity\EntityTeleportEvent' to 'SAC v3.5.2':Call to a member function getName() on null at DarkWav\SAC\EventListener
[12:16:39] [Server thread/CRITICAL]: Error: "Call to a member function getName() on null" (EXCEPTION) in "SAC/src/DarkWav/SAC/Observer" at line 1550

**Comment by DarkWav** [comment] 2018-08-18 18:56
Thanks for Bug reporting!
The bad news: Im currently on holiday until next friday and unable to change or fix anything until then.
The Good news: 
The bug is not critical and won't affect your server asides spamming the console.
The plugin will still function as usual.
I will fix this ASAP (in my case in 6 days), until than you'll have to wait.

**Comment by Reflyansyah** [comment] 2018-08-19 09:18
Happy holiday hahahaha

**Comment by DarkWav** [comment] 2018-08-21 06:29
Thanks :D

**Comment by DarkWav** [comment] 2018-08-25 08:56
Hopefully fixed with version 3.5.3.
I cannot guarantee since i could not reproduce the crash.
Please make sure to update to this version.
If the problem isn't solved, please reply to this issue or open a new one.
If you have any further questions, feel free to ask them.

**Closed as completed by DarkWav** 2018-08-25 08:56 UTC
Labels: BUG, Solved, Minor, Confirmed
