### ISSUE TITLE
Slime block

### ISSUE THREAD

**Issue by YHC2538** [DarkWav/SAC#84] opened 2018-08-23 04:25 UTC
When you jump down from a really high platform and land on the slime block, you bounce up very high, and it kicks you for flying.

**Comment by Reflyansyah** [comment] 2018-08-24 00:47
Fly-Treshold : 25

**Comment by DarkWav** [comment] 2018-08-24 11:05
Thanks for bug reporting!
It seems like PMMP implemented th slime block now (used to not be implemented), i will fix this ASAP.

**Comment by DarkWav** [comment] 2018-08-25 08:55
Fixed with version 3.5.3.
You can now configure the SlimeSeconds value in the config for your needs.
Please make sure to update to this version.
If the problem isn't solved, please reply to this issue or open a new one.
If you have any further questions, feel free to ask them.

**Closed as completed by DarkWav** 2018-08-25 08:55 UTC
Labels: BUG, EMERGENCY, Solved, Confirmed
