### ISSUE TITLE
AntiFly not working

### ISSUE THREAD

**Issue by atTheDisco** [DarkWav/SAC#89] opened 2018-10-27 21:52 UTC
Anti fly "Altay 4.0.0+dev for Minecraft: Bedrock Edition v1.7.0 (protocol version 291)" not working in version. Flying players do not detect SAC.

**Comment by DarkWav** [comment] 2018-10-28 05:35
Is it working on any stable release of PocketMine-MP or Altay?
Because SAC was not made to run on developent builds, I can't always guarantee that everything works on them stright away, but i will take a look at this....

**Comment by DarkWav** [comment] 2018-10-28 05:54
How did you test fly? With a Hacked Client or with a server plugin?
Server plugins are supposed to allow people to fly and thats why AntiCheats dont detect server-side plugins which allow you to fly.

**Comment by DarkWav** [comment] 2018-10-28 06:09
OK sorry, i now know what the problem is, its a real "BUG" and should happen on any pmmp server.
I will fix this ASAP.

**Comment by DarkWav** [comment] 2018-10-28 06:38
I hope this is fixed with SAC 3.6.3.
Make sure to upgrade to SAC 3.6.3 (Replace SAC_vx.x.x.phar).
If the bug still happens, please reply to this issue or open a new one.

**Closed as completed** 2018-10-28 06:39 UTC
Labels: BUG, EMERGENCY, Solved, Confirmed
