### ISSUE TITLE
kicked for flying

### ISSUE THREAD

**Issue by Matthww** [DarkWav/SAC#67] opened 2018-03-17 18:05 UTC
Whenever you "combo" someone and they stay up in the air because of the knockback they will get detected by the fly detection.

**Comment by DarkWav** [comment] 2018-03-18 06:39
Tanks for Bug Reporting! I will fix this ASAP. Sorry for the inconvenience!

**Comment by DarkWav** [comment] 2018-03-18 07:07
fixed with commit 609e06dbb4775072e485bf11ad9614a1493eddb6 / Version 3.3.5.
Please make sure to update to version 3.3.5.
If this bug still happens then, comment on the issue or open a new one.

**Comment by Matthww** [comment] 2018-07-06 09:55
This is happening again.

**Comment by DarkWav** [comment] 2018-07-06 11:21
Thanks for Bug Reporting!
I will take a look at this ASAP.

**Comment by DarkWav** [comment] 2018-07-06 12:30
Reproduced.
Seems like I updated the API the wrong way xD!
I will fix this ASAP ;)

**Comment by DarkWav** [comment] 2018-07-06 13:03
Hopefully fixed with commit 503221e5c92bf36c6c3c4879ca95b96da1de70ff / Version 3.4.4
Please make sure to update to this version!
If the issue is not fixed, please reply to this issue or open a new one.

**Closed as completed by DarkWav** 2018-07-06 13:03 UTC
Labels: BUG, EMERGENCY, Solved, Confirmed
